<template>
  <b-form @submit="postSecret">
    <b-form-group label="Secret:" label-for="secret-textarea">
      <b-form-textarea
        id="secret-textarea"
        v-model="secret"
        rows="20"
        max-rows="20"
      ></b-form-textarea>
    </b-form-group>

    <b-form-group label="Expiration (local time):" label-for="datepicker">
      <b-row>
        <b-col>
          <b-input-group id="datepicker">
            <b-form-input
              v-model="expirationDate"
              type="text"
              placeholder="YYYY-MM-DD"
              autocomplete="off"
              required
            ></b-form-input>
            <b-input-group-append variant="primary">
              <b-form-datepicker
                v-model="expirationDate"
                button-only
                right
                locale="en-US"
                button-variant="outline-primary"
              ></b-form-datepicker>
            </b-input-group-append>
          </b-input-group>
        </b-col>
        <b-col>
          <b-input-group>
            <b-form-input
              v-model="expirationTime"
              type="text"
              placeholder="HH:mm:ss"
              required
            ></b-form-input>
            <b-input-group-append>
              <b-form-timepicker
                v-model="expirationTime"
                button-only
                right
                locale="en"
                button-variant="outline-primary"
                show-seconds
                :hour12="false"
              ></b-form-timepicker>
            </b-input-group-append>
          </b-input-group>
        </b-col>
      </b-row>
    </b-form-group>
    <b-button type="submit" block variant="outline-primary">Create secret link</b-button>
  </b-form>
  <br />
  <h2>How it works</h2>
  <p>
    Simple One Time Secret is an application that allows to securely share information using a
    single-use link. Once the secret has been viewed (or once the expiration is reached), the secret
    is deleted from the database and no longer accessible. In addition, the server only has access
    to the encrypted secret and its ID. Everything else is generated client side and is never sent
    to the server. More precisely:
  </p>
  <ol>
    <li>A random 256-bit encryption key is generated in the browser using the Web Crypto API.</li>
    <li>
      The secret is encrypted with AES-256-GCM (authenticated encryption) using a fresh random IV.
    </li>
    <li>The encrypted secret is sent to the server, along with the expiration timestamp.</li>
    <li>The server replies with the ID of the secret.</li>
    <li>
      A link is generated by appending the ID and the base64url-encoded key to the URL fragment.
      Hash data is not sent to the server when a URL is accessed.
    </li>
    <li>
      When the secret is retrieved, the server receives the ID of the secret, deletes it from the
      database, and returns the encrypted value back to the client (if it's not expired).
    </li>
    <li>
      The secret value can then be decrypted client side using the key stored in the hash data.
    </li>
  </ol>
  <p>
    Want more information? Good news,
    <b-link href="https://github.com/daxAKAhackerman/simple-one-time-secret"
      >this project is open source!
    </b-link>
  </p>
</template>
<script>
import axios from 'axios'
import { store } from '@/store.js'
import { makeToast } from '@/helpers.js'
import { bytesToBase64Url } from '@/crypto.js'

export default {
  name: 'NewSecret',
  data() {
    return {
      secret: '',
      expirationDate: '',
      expirationTime: '00:00:00',
      store
    }
  },
  computed: {
    expirationTimestamp() {
      let expirationTime = this.expirationTime
      if (expirationTime === '') {
        expirationTime = '00:00:00'
      }
      const expirationString = `${this.expirationDate} ${expirationTime}`
      const expirationDate = new Date(expirationString)
      const expirationFormated = Math.floor(expirationDate.getTime() / 1000)

      return expirationFormated
    }
  },
  methods: {
    initNewSecret() {
      const currentDate = new Date()
      currentDate.setDate(currentDate.getDate() + 7)
      currentDate.setTime(currentDate.getTime() - currentDate.getTimezoneOffset() * 60 * 1000)

      this.expirationDate = currentDate.toISOString().split('T')[0]
      this.expirationTime = '00:00:00'
      this.secret = ''
    },
    async postSecret(event) {
      event.preventDefault()
      try {
        const keyBytes = crypto.getRandomValues(new Uint8Array(32))
        const ciphertext = await this.encryptSecret(this.secret, keyBytes)

        const payload = { expiration: this.expirationTimestamp, secret: ciphertext }
        const response = await axios.post('/api/secret', payload)

        this.generateLink(response.data.id, keyBytes)
        this.initNewSecret()
      } catch (error) {
        void error
        makeToast(
          this,
          'Something went wrong while creating your secret. Please make sure that the expiration date/time is valid.',
          'danger'
        )
      }
    },
    async encryptSecret(secret, keyBytes) {
      const key = await crypto.subtle.importKey('raw', keyBytes, { name: 'AES-GCM' }, false, [
        'encrypt'
      ])
      const iv = crypto.getRandomValues(new Uint8Array(12))
      const plaintext = new TextEncoder().encode(secret)
      const ciphertext = new Uint8Array(
        await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, plaintext)
      )

      const combined = new Uint8Array(iv.length + ciphertext.length)
      combined.set(iv, 0)
      combined.set(ciphertext, iv.length)

      let binary = ''
      for (const b of combined) binary += String.fromCharCode(b)
      return btoa(binary)
    },
    generateLink(uuid, keyBytes) {
      const link = `${window.location.origin}/#${uuid}.${bytesToBase64Url(keyBytes)}`
      this.store.setLink(link)
    }
  },
  created() {
    this.initNewSecret()
  }
}
</script>
